// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift/assisted-image-service/pkg/imagestore (interfaces: ImageStore)

// Package imagestore is a generated GoMock package.
package imagestore

import (
	context "context"
	io "io"
	reflect "reflect"

	isoeditor "github.com/openshift/assisted-image-service/pkg/isoeditor"
	gomock "go.uber.org/mock/gomock"
)

// MockImageStore is a mock of ImageStore interface.
type MockImageStore struct {
	ctrl     *gomock.Controller
	recorder *MockImageStoreMockRecorder
}

// MockImageStoreMockRecorder is the mock recorder for MockImageStore.
type MockImageStoreMockRecorder struct {
	mock *MockImageStore
}

// NewMockImageStore creates a new mock instance.
func NewMockImageStore(ctrl *gomock.Controller) *MockImageStore {
	mock := &MockImageStore{ctrl: ctrl}
	mock.recorder = &MockImageStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageStore) EXPECT() *MockImageStoreMockRecorder {
	return m.recorder
}

// CreateHTTPReader mocks base method.
func (m *MockImageStore) CreateHTTPReader(arg0 string) (io.ReadSeekCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHTTPReader", arg0)
	ret0, _ := ret[0].(io.ReadSeekCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHTTPReader indicates an expected call of CreateHTTPReader.
func (mr *MockImageStoreMockRecorder) CreateHTTPReader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHTTPReader", reflect.TypeOf((*MockImageStore)(nil).CreateHTTPReader), arg0)
}

// GetOVEOffsets mocks base method.
func (m *MockImageStore) GetOVEOffsets(arg0, arg1 string) *isoeditor.OVEOffsets {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOVEOffsets", arg0, arg1)
	ret0, _ := ret[0].(*isoeditor.OVEOffsets)
	return ret0
}

// GetOVEOffsets indicates an expected call of GetOVEOffsets.
func (mr *MockImageStoreMockRecorder) GetOVEOffsets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOVEOffsets", reflect.TypeOf((*MockImageStore)(nil).GetOVEOffsets), arg0, arg1)
}

// HTTPChunkSize mocks base method.
func (m *MockImageStore) HTTPChunkSize() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPChunkSize")
	ret0, _ := ret[0].(int64)
	return ret0
}

// HTTPChunkSize indicates an expected call of HTTPChunkSize.
func (mr *MockImageStoreMockRecorder) HTTPChunkSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPChunkSize", reflect.TypeOf((*MockImageStore)(nil).HTTPChunkSize))
}

// HaveVersion mocks base method.
func (m *MockImageStore) HaveVersion(arg0, arg1 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HaveVersion", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HaveVersion indicates an expected call of HaveVersion.
func (mr *MockImageStoreMockRecorder) HaveVersion(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HaveVersion", reflect.TypeOf((*MockImageStore)(nil).HaveVersion), arg0, arg1)
}

// NmstatectlPathForParams mocks base method.
func (m *MockImageStore) NmstatectlPathForParams(arg0, arg1 string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NmstatectlPathForParams", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NmstatectlPathForParams indicates an expected call of NmstatectlPathForParams.
func (mr *MockImageStoreMockRecorder) NmstatectlPathForParams(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NmstatectlPathForParams", reflect.TypeOf((*MockImageStore)(nil).NmstatectlPathForParams), arg0, arg1)
}

// PathForParams mocks base method.
func (m *MockImageStore) PathForParams(arg0, arg1, arg2 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PathForParams", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// PathForParams indicates an expected call of PathForParams.
func (mr *MockImageStoreMockRecorder) PathForParams(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PathForParams", reflect.TypeOf((*MockImageStore)(nil).PathForParams), arg0, arg1, arg2)
}

// Populate mocks base method.
func (m *MockImageStore) Populate(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Populate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Populate indicates an expected call of Populate.
func (mr *MockImageStoreMockRecorder) Populate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Populate", reflect.TypeOf((*MockImageStore)(nil).Populate), arg0)
}

// URLForParams mocks base method.
func (m *MockImageStore) URLForParams(arg0, arg1, arg2 string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URLForParams", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	return ret0
}

// URLForParams indicates an expected call of URLForParams.
func (mr *MockImageStoreMockRecorder) URLForParams(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLForParams", reflect.TypeOf((*MockImageStore)(nil).URLForParams), arg0, arg1, arg2)
}

